### ISSUE TITLE
Need to create staging/apis directory

### ISSUE THREAD

**Issue by medgar-nitric** [nitrictech/legacy-cli#164] opened 2021-09-02 03:56 UTC
Observed the CLI not creating .nitric/staging/apis directory during run:

```bash
medgar@Mal-Laptop2:~/nitric/project-templates/java-service$ nitric-dev run
✔ Building Services
✔ Creating docker network
✔ Creating Volume: example-java-service-vol-551af626
✔ Running Functions & Containers
⚠ Starting API Gateways
  ✖ Creating API Gateways
    › ENOENT: no such file or directory, mkdir '/home/medgar/.nitric/staging/apis'
✔ Starting Entrypoints
 Function Port
 ──────── ─────
 create   40663
 list     39353
 read     45233
 Api     Port
 ─────── ─────
 example 49152
Exiting, please wait... done
```

Once the directory was created manually worked.

**Comment by tjholm** [comment] 2021-10-20 00:29
Duplicate of #157

**Closed as completed by tjholm** 2021-10-20 00:29 UTC
Labels: bug
